name: context7-mcp-server
region: fra

services:
  - name: mcp-server
    source_dir: /
    http_port: 8080
    environment_slug: python
    instance_size_slug: basic-xxs
    instance_count: 1

    # Procfile wird automatisch erkannt (web: python main.py)
    # run_command wird NICHT benötigt bei Procfile

    routes:
      - path: /

    envs:
      - key: PORT
        value: "8080"
      - key: PYTHONUNBUFFERED
        value: "1"

    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3 